### ISSUE TITLE
About spconv

### ISSUE THREAD

**Issue by cainiaoshidai** [dsc1126/RPGN#1]
Hi, 
    It's excellent work. I saw in the readme that we need to use your modified `spvconv`. But I didn't find it in your code. May be I didn't notice. I downloaded `spconv1.2.2` from the github homepage of spconv, and I don't know if it will affect the results.
Forward your reply.
Best.
![1679396117011](https://user-images.githubusercontent.com/49551022/226585998-2df712a3-12fe-40cb-ad5e-5b7bc1ffebec.jpg)

**Comment by dsc1126** [comment]
Hi,
Thank you for your interest in our work. You may directly use latest spconv, since they have added .contiguous() to grad_output. I have tested with spconv 1.2.1, the results are not affected.

**Comment by cainiaoshidai** [comment]
Thanks, I will have a try.
